# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        haxe-version:
          # - stable
          - nightly
        target:
          - node
          - jvm

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v1
        with:
          node-version: "10"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache Haxe
        uses: actions/cache@v1
        with:
          path: ~/haxe
          key: haxe

      - uses: lix-pm/setup-lix@master
      - run: lix install haxe ${{ matrix.haxe-version }}
      - run: lix download
      - run: |
          git clone --depth 1 https://github.com/facebook/buck.git
          pushd buck
          ant
          echo "::set-env name=PATH::$PATH:$(pwd)/bin"
          popd
        if: ${{ matrix.target == 'jvm' }}
      - run: lix run travix ${{ matrix.target }}
